- name: Adding hashicorp repo
  shell: |
    if [ ! -f /usr/share/keyrings/hashicorp-archive-keyring.gpg ]; then
    wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg --yes &&
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list &&
    sudo apt update;
    fi

- name: Install consul
  apt:
    name: consul
    state: present
    
- name: Create Consul directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: consul
    group: consul
  with_items:
    - /opt/consul
    - /etc/consul.d
  become: yes

- name: Copy Consul server config
  ansible.builtin.copy:
    src: "consul_server.hcl"
    dest: "/etc/consul.d/consul.hcl"
    owner: consul
    group: consul
  become: yes

- name: Create systemd service for Consul
  ansible.builtin.copy:
    dest: /etc/systemd/system/consul.service
    content: |
      [Unit]
      Description=Consul Agent
      Requires=network-online.target
      After=network-online.target

      [Service]
      User=consul
      Group=consul
      ExecStart=/usr/bin/consul agent -config-dir=/etc/consul.d/ -data-dir=/opt/consul
      ExecReload=/bin/kill -HUP $MAINPID
      KillSignal=SIGTERM
      Restart=on-failure
      LimitNOFILE=4096

      [Install]
      WantedBy=multi-user.target
  notify: restart consul
  become: yes

- name: Start and enable Consul service
  ansible.builtin.systemd:
    name: consul
    enabled: yes
    state: started
  become: yes
