global:
  scrape_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - '192.168.50.10:9100'
        - '192.168.50.11:9100'
        - '192.168.50.12:9100'
  
  # Node exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets: 
        - '192.168.50.10:9100'
        - '192.168.50.11:9100'
        - '192.168.50.12:9100'

  # Blackbox exporter
  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.50.10:9115

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: 
        - '192.168.50.10:8080'
        - '192.168.50.11:8080'
        - '192.168.50.12:8080'

  # Spring Boot applications (например, booking-service)
  - job_name: 'spring-boot-apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - '192.168.50.10:8083'
          - '192.168.50.10:8087'
          - '192.168.50.10:8084'
          - '192.168.50.10:8085'
          - '192.168.50.10:8082'
          - '192.168.50.10:8081'
          - '192.168.50.10:8086'


  - job_name: 'rabbitmq'
    static_configs:
      - targets:
          - '192.168.50.10:9419'

rule_files:
  - alert_rules.yaml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '192.168.50.10:9093'

