---
- hosts: consul_server
  become: yes
  roles:
    - install_consul_server 


- hosts: db
  become: yes
  roles:
    - install_consul_client
    - install_db


- hosts: api
  become: yes
  roles:
    - install_consul_client
    - install_hotels_service
