---
- name: Install python3-psycopg2
  apt:
    name: python3-psycopg2
    state: present
  become: true

- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes
  become: true

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes
  become: true

- name: Create PostgreSQL database
  postgresql_db:
    name: postgres
    state: present
  become: true

- name: Create a new table
  postgresql_query:
    db: postgres
    query: "CREATE TABLE test_table (id SERIAL PRIMARY KEY, name VARCHAR(50), age INT);"

- name: Insert data into the table
  postgresql_query:
    db: postgres
    query: |
      INSERT INTO test_table (name, age) VALUES ('Alice', 30);
      INSERT INTO test_table (name, age) VALUES ('Bob', 25);
      INSERT INTO test_table (name, age) VALUES ('Charlie', 35);

